### ISSUE TITLE
Assignment 1 ready for grading!

### ISSUE THREAD

**Issue by sivilyslare** [VIS-2129-F2020/cschmidt-vis#1]
Hi! My first assignment is ready under the assignment1.rmd and assignment1.html filenames!

**Comment by bauranov** [comment]
- When you upload csv it's useful to print the header and first several rows to see what data is available. You can do that with head() function.
- Lines 40-45 (Box plot): it's not clear what catvchildren means. All chart elements should have proper names. 
- Histogram #7: when you have one value that overshadows the rest, it sometimes makes sense to plot two charts, with and without that value. That way, the distribution of hours>0 is more legible. 
- Count plot #9: If the variable only makes sense as a whole number (like the number of children), make sure to change the labels on the axis to represent that. Labels can be changed with scale_x_discrete(breaks, labels)
- Line 134: Make sure that labels and titles make sense. 

Keep up the good work!
